env:
  browser: true
  es6: true
  jquery: true
extends: 'eslint:all'
parserOptions:
  ecmaVersion: 2021
  sourceType: script
  ecmaFeatures:
    jsx: true
rules:
  indent:
  - error
  - tab
  linebreak-style:
  - error
  - unix
  quotes:
  - error
  - single
  semi:
  - error
  - always
  no-undef: 0
  no-unused-vars: 0
