#############
# stylelint #
#############
# [OVERVIEW] CSS linter:
# https://stylelint.io/
#
# [INFO] Stylelint configuration:
# https://stylelint.io/user-guide/configuration
extends:

#########################
# stylelint-config-html #
#########################
# [OVERVIEW] Recommended configuration, checks for avoid errors:
# https://www.npmjs.com/package/stylelint-config-recommended
#
# [INFO] Avoid errors list:
# https://stylelint.io/user-guide/rules/list/#avoid-errors
- stylelint-config-recommended


###################################
# no-unsupported-browser-features #
###################################
# [OVERVIEW] Check features for browsers that supported in “browserslist” file:
# https://www.npmjs.com/package/stylelint-no-unsupported-browser-features
plugins:
- stylelint-no-unsupported-browser-features


rules:
  # [INFO] Rule description:
  # https://stylelint.io/user-guide/rules/no-descending-specificity
  #
  # [WARNING] Autoprefixer create duplicates → stylelint show errors:
  # https://stackoverflow.com/q/58057777/5951529
  # https://github.com/postcss/autoprefixer/issues/1196
  #
  # [INFO] Use “null”, not “false” for disabling rule:
  # https://stylelint.io/user-guide/configuration#rules
  no-descending-specificity: null

  # [REQUIRED] “plugin/plugin_name: true”
  # https://www.npmjs.com/package/stylelint-no-unsupported-browser-features#recommendations
  plugin/no-unsupported-browser-features: true
