language: node_js

node_js:
  - "node"

env:
  - GRUNT_COMMAND=default
  - GRUNT_COMMAND=publish

install:
  - npm install -g grunt-cli
  - npm install

script:
  - grunt $GRUNT_COMMAND
