clone_depth: 1

init:
- SET PATH=%PATH%;%PYTHON%;%PYTHON%\Scripts
- refreshenv

configuration:
- Debug
- Release

environment:
  PYTHON: C:\Python37-x64
  PYTHON_VERSION: 3.7
  PYTHON_ARCH: 64
  KIRA_VARIABLE: Queen

build_script:
- echo %KIRA_VARIABLE%
- python --version

for:
-
  matrix:
    only:
    - configuration: Release
  environment:
    KIRA_VARIABLE: Goddess