environment:

  matrix:

    - GRUNT_COMMAND: default
    - GRUNT_COMMAND: publish

install:

  - choco install nodejs -y
  - npm install -g grunt-cli
  - npm install

build_script:

  - grunt %GRUNT_COMMAND%