platform: x64

image: Visual Studio 2022

clone_depth: 1

environment:
  nodejs_version: "21"
  PYTHON: C:\Python312-x64


cache:
# - C:\ProgramData\chocolatey\bin
# - C:\ProgramData\chocolatey\lib
- "%USERPROFILE%\\AppData\\Roaming\\npm"
# - "%APPVEYOR_BUILD_FOLDER%\\node_modules"
- "%PYTHON%\\Lib\\site-packages"
- "%PYTHON%\\Scripts"
# - "%APPVEYOR_BUILD_FOLDER%\\.venv\\Lib\\site-packages"
# - "%APPVEYOR_BUILD_FOLDER%\\.venv\\Scripts"

init:
- SETX APPVEYOR_SAVE_CACHE_ON_ERROR true
- SETX /m PATH "%PATH%;%PYTHON%\Scripts"

install:
# - reg import appveyor/EnableUnicodeUTF8Worldwide.reg
# - shutdown /r /t 0
# - ps: Restart-Computer
# - timeout 10
# - reg import appveyor/EnableChcp65001.reg
# - choco install html-tidy --version=5.6.0 --allow-downgrade --ignore-dependencies
# - npm install --global htmlhint
- npm install --global @axe-core/cli fkill-cli http-server
- "%PYTHON%\\python -m pip install linkchecker"

before_build:
# - chcp
# - node --version
# - tidy --version
# - htmlhint --version
# - htmllint --version
- echo %PATH%
- Start-Process "cmd" -ArgumentList "/c http-server port 4147"

build_script:
# - htmlhint KiraValidHTML.html
# - htmlhint КираВалидныйHTML.html
# - htmllint KiraValidHTML.html
# - htmllint КираВалидныйHTML.html
# - tidy --quiet yes KiraValidHTML.html
# - tidy --quiet yes КираВалидныйHTML.html
- axe http://localhost:4147/KiraTestedHTML.html
- linkchecker http://localhost:4147/KiraTestedHTML.html
- fkill :4147 --force
- linkchecker http://localhost:4147/KiraTestedHTML.html
