platform: x64

image: Visual Studio 2022

clone_depth: 1

environment:
  PYTHON: C:\Python312-x64

# cache:
# - "%LOCALAPPDATA%\\Temp\\chocolatey"
# - C:\ProgramData\chocolatey\bin
# - C:\ProgramData\chocolatey\lib
# - "%USERPROFILE%\\AppData\\Roaming\\npm"
# - "%APPVEYOR_BUILD_FOLDER%\\node_modules"
# - "%LOCALAPPDATA%\\pip\\cache"
# - "%LOCALAPPDATA%\\pipenv\\pipenv\\cache"
# - "%APPVEYOR_BUILD_FOLDER%\\.peru\\cache"
# - "%LOCALAPPDATA%\\npm-cache"

init:
- SETX APPVEYOR_SAVE_CACHE_ON_ERROR true
- SETX NODE_NO_WARNINGS 1
# - SETX PIPENV_IGNORE_VIRTUALENVS 1
# - SETX PIPENV_SKIP_LOCK 1
# - SETX PIPENV_VENV_IN_PROJECT 1
# - SETX PYTHONIOENCODING utf-8
# - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

install:
# - reg import appveyor/EnableUnicodeUTF8Worldwide.reg
# - shutdown /r /t 0
# - reg import appveyor/EnableChcp65001.reg
- choco install --yes nodejs
# - choco upgrade --yes chocolatey
- refreshenv
# - pathed /MACHINE /ADD %PYTHON%
# - pathed /MACHINE /ADD %PYTHON%\Scripts
# - refreshenv
- npm config get cache
- npm install --global grunt-cli
- npm ci --loglevel=error
# - choco install --yes chocolatey.config
# - pipenv install --dev --verbose

before_build:
# - where fd
# - fd --version
# - where node
# - node --version
# - where tidy
# - tidy --version
# - where pipenv
- where node
- where npm
- where npx
- where grunt

build_script:
- node --version
- npm --version
- npx --version
- grunt --version
