init:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - set PYTHONIOENCODING=utf-8

environment:
  nodejs_version: "9.4.0"

  matrix:

    - PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: "3.6.4"
      PYTHON_ARCH: "64"

platform: x64

build_script:

  - node --version