platform: x64

clone_depth: 1

init:
- SETX PIPENV_IGNORE_VIRTUALENVS 1
- SETX PIPENV_VENV_IN_PROJECT 1
# [FIXME] Use pathed instead of SETX;
# user can loss data, if PATH contains more than 1024 symbols:
# https://superuser.com/a/939256/572069
# http://www.p-nand-q.com/download/gtools/pathed.html
# [LEARN] SETX PATH:
# https://stackoverflow.com/a/26947177/5951529
# https://superuser.com/a/939256/572069
# [WARNING] Needs, because will get messages as:
# «flake8 is not recognized»
# https://github.com/ogrisel/python-appveyor-demo/blob/master/appveyor.yml
# Python 2 by default, see:
# https://www.appveyor.com/docs/build-environment/#python
# https://ci.appveyor.com/project/Kristinita/erichek/build/1.0.3
- SETX PATH "%PATH%;%PYTHON%;%PYTHON%\Scripts"
# Needs AppVeyor console set, see:
# https://stackoverflow.com/a/48093971/5951529
- SETX PYTHONIOENCODING utf-8
# Set latest Ruby version at the time:
# https://www.appveyor.com/docs/lang/ruby/
# https://www.appveyor.com/docs/build-environment/#ruby
- SETX PATH "%PATH%;C:\Ruby25-x64\bin"
# [INFO] Set LocalAppVeyor Windows path:
# DotNet user profile is “USERPROFILE” on Windows and “HOME” on Linux:
# https://github.com/dotnet/cli/issues/7569#issuecomment-329280924
- SETX PATH "%PATH%;%USERPROFILE%\.dotnet\tools"
# [INFO] Remove .NET Core SDK telemetry
- SETX DOTNET_CLI_TELEMETRY_OPTOUT 1
# Use “CALL Refreshenv.cmd” for local installation:
# https://github.com/chocolatey/choco/issues/1461#issuecomment-348136706
# https://ss64.com/nt/call.html
- refreshenv

configuration:
- Debug
- Release

environment:
  APPVEYOR_API_KEY:
    secure: +tAYCLWvKpNefBmIFHBZzSdFnN8mu71hBU1MqYbrjlY=

install:
- dotnet tool install -g localappveyor --version 0.5.0-alpha.10

build_script:
- echo %PATH%
- cd "%USERPROFILE%\.dotnet\tools" && tree /f

test_script:
- LocalAppVeyor lint --token %APPVEYOR_API_KEY%
