platform: x64

image: Visual Studio 2022

clone_depth: 1

environment:
  APPVEYOR_SAVE_CACHE_ON_ERROR: true
  nodejs_version: "21"
  PYTHON: C:\Python312-x64


cache:
- C:\ProgramData\chocolatey\bin
- C:\ProgramData\chocolatey\lib
- "%USERPROFILE%\\AppData\\Roaming\\npm"
# - "%APPVEYOR_BUILD_FOLDER%\\node_modules"
- "%PYTHON%\\Lib\\site-packages"
- "%PYTHON%\\Scripts"
# - "%APPVEYOR_BUILD_FOLDER%\\.venv\\Lib\\site-packages"
# - "%APPVEYOR_BUILD_FOLDER%\\.venv\\Scripts"

init:
# - SETX /m PATH "%PATH%;%PYTHON%\Scripts"

install:
# - reg import appveyor/EnableUnicodeUTF8Worldwide.reg
# - shutdown /r /t 0
# - ps: Restart-Computer
# - timeout 10
# - reg import appveyor/EnableChcp65001.reg
# - choco install html-tidy --version=5.6.0 --allow-downgrade --ignore-dependencies
# - npm install --global htmlhint
- npm install --global @axe-core/cli fkill-cli http-server pa11y-ci
- "%PYTHON%\\python -m pip install linkchecker"
- choco install googlechrome --yes
- choco install gtools --yes --force
- refreshenv
# - where pathed
- pathed /APPEND %PYTHON% /USER
- pathed /APPEND %PYTHON%\Scripts /USER
- refreshenv


before_build:
# - chcp
# - node --version
# - tidy --version
# - htmlhint --version
# - htmllint --version
# - echo %PATH%
- pa11y-ci --version
- linkchecker --version
- where start
# - start /b cmd /c http-server --port 4147
- "%APPVEYOR_BUILD_FOLDER%/appveyor/Daemons.bat"

build_script:
# - htmlhint KiraValidHTML.html
# - htmlhint КираВалидныйHTML.html
# - htmllint KiraValidHTML.html
# - htmllint КираВалидныйHTML.html
# - tidy --quiet yes KiraValidHTML.html
# - tidy --quiet yes КираВалидныйHTML.html
- pa11y-ci http://localhost:4147/KiraTestedHTML.html
- linkchecker http://localhost:4147/KiraTestedHTML.html
- fkill :4147 --force
# - linkchecker http://localhost:4147/KiraTestedHTML.html
