environment:

  matrix:

    - PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: "3.6.4"
      PYTHON_ARCH: "64"

platform: x64

init:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

install:
  - python -m pip install -U pip
  - pip install pipenv
  - pipenv install --dev

build_script:

  - pip --version
  - pipenv --version
  - pelican --version