clone_depth: 1

platform: x64

environment:
  PYTHON: C:\Python37-x64
  RUBY: C:\Ruby26-x64\bin

install:
- choco install gtools -y

build_script:
- pathed /APPEND %PYTHON% %RUBY%
- echo %PATH%
- dir "C:\Program Files (x86)\p-nand-q.com\GTools" /b /s /A-D