clone_depth: 1

platform: x64

environment:
  PYTHON: C:\Python37-x64
  RUBY: C:\Ruby26-x64\bin

init:
- SETX GRUNT_PYLINT_SKIP_POSTINSTALL yes

install:
- choco install gtools -y
- refreshenv
- pathed /APPEND %PYTHON% /USER
- pathed /APPEND %RUBY% /USER
- refreshenv

build_script:
- echo %PATH%
- echo %GRUNT_PYLINT_SKIP_POSTINSTALL%