platform: x64

image: Visual Studio 2022

clone_depth: 1

environment:
  PYTHON: C:\Python312-x64

cache:
# - C:\ProgramData\chocolatey\bin
# - C:\ProgramData\chocolatey\lib
# - "%USERPROFILE%\\AppData\\Roaming\\npm"
# - "%APPVEYOR_BUILD_FOLDER%\\node_modules"
- "%LocalAppData%\\pip\\cache"
- "%LocalAppData%\\pipenv\\pipenv\\cache"

init:
# [REQUIRED] “true”, not “1”
- SETX APPVEYOR_SAVE_CACHE_ON_ERROR true
# - SETX PIPENV_IGNORE_VIRTUALENVS 1
# - SETX PIPENV_VENV_IN_PROJECT 1
# - SETX PIPENV_SKIP_LOCK 1
# - SETX PYTHONIOENCODING utf-8
# - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

install:
# - reg import appveyor/EnableUnicodeUTF8Worldwide.reg
# - shutdown /r /t 0
# - reg import appveyor/EnableChcp65001.reg
- choco install --yes gtools
- refreshenv
- pathed /MACHINE /ADD %PYTHON%
- pathed /MACHINE /ADD %PYTHON%\Scripts
- refreshenv
- pip install pipenv
- pipenv install --dev --verbose

before_build:
- where python
- python --version
- where pip
- pip --version
- where pipenv

build_script:
- pipenv --version
