platform: x64

image: Visual Studio 2022

clone_depth: 1

environment:
  APPVEYOR_SAVE_CACHE_ON_ERROR: true
  nodejs_version: "21"


cache:
# - C:\ProgramData\chocolatey\bin
# - C:\ProgramData\chocolatey\lib
- "%USERPROFILE%\\AppData\\Roaming\\npm"
# - "%APPVEYOR_BUILD_FOLDER%\\node_modules"
# - "%PYTHON%\\Lib\\site-packages"
# - "%PYTHON%\\Scripts"
# - "%APPVEYOR_BUILD_FOLDER%\\.venv\\Lib\\site-packages"
# - "%APPVEYOR_BUILD_FOLDER%\\.venv\\Scripts"

# init:
# - SETX /m PATH "%PATH%;%PYTHON%\Scripts"


install:
# - reg import appveyor/EnableUnicodeUTF8Worldwide.reg
# - shutdown /r /t 0
# - ps: Restart-Computer
# - timeout 10
# - reg import appveyor/EnableChcp65001.reg
- npm install --global fkill-cli http-server


before_build:
- node --version
- fkill --version
- http-server --version


build_script:
- powershell -Command "Start-Process cmd -ArgumentList '/c http-server --port 4147'"
- fkill :4147 --force --verbose
