init:
- set PATH=%GOPATH%\bin;c:\go\bin;%PATH%

environment:
  GOPATH: c:\gopath

build_script:

- mkdir c:\gopath\src\github.com\mattn
- cd c:\gopath\src\github.com\mattn
- git clone -b windows https://github.com/mattn/asciinema
- cd asciinema
- git checkout windows
- go build