platform: x64

image: Visual Studio 2022

clone_depth: 1

cache:
- C:\ProgramData\chocolatey\bin
- C:\ProgramData\chocolatey\lib
# - "%USERPROFILE%\\AppData\\Roaming\\npm\\node_modules"
# - "%APPVEYOR_BUILD_FOLDER%/node_modules"

# environment:
#   nodejs_version: "21"

init:
- ps: GET-WinSystemLocale
- ps: Set-WinSystemLocale ru-RU
- ps: Start-Sleep -s 5; Restart-Computer
- ps: Start-Sleep -s 5

install:
- choco install html-tidy --version=5.6.0 --allow-downgrade --ignore-dependencies
- reg import KiraUnicodeCmd.reg

before_build:
- where ls
- where dir
- ps: GET-WinSystemLocale

build_script:
- chcp
- ls
- dir
- ps: tidy --quiet yes KiraValidHTML.html
- ps: tidy --quiet yes КираВалидныйHTML.html
