platform: x64

image: Visual Studio 2022

clone_depth: 1

environment:
  APPVEYOR_SAVE_CACHE_ON_ERROR: true
  # NODE_TLS_REJECT_UNAUTHORIZED: 0
  # nodejs_version: "21"
  # PATH: "%PYTHON%;%PYTHON%\\Scripts;C:\\Program Files\\gnuplot\\bin;$(PATH)"
  PYTHON: C:\Python312-x64


cache:
# - C:\ProgramData\chocolatey\bin
# - C:\ProgramData\chocolatey\lib
# - "%USERPROFILE%\\AppData\\Roaming\\npm"
# - "%APPVEYOR_BUILD_FOLDER%\\node_modules"
- "%PYTHON%\\Lib\\site-packages"
- "%PYTHON%\\Scripts"
# - "%APPVEYOR_BUILD_FOLDER%\\.venv\\Lib\\site-packages"
# - "%APPVEYOR_BUILD_FOLDER%\\.venv\\Scripts"

# init:
# - SETX NODE_TLS_REJECT_UNAUTHORIZED 0
# - SETX /m PATH "%PATH%;%PYTHON%\Scripts"

install:
- echo %PATH%
- choco install --yes gtools
- refreshenv
- pathed /APPEND %PYTHON% /USER
- pathed /APPEND %PYTHON%\Scripts /USER
- choco install --yes gnuplot
- echo %PATH%
- refreshenv
- pip install linkchecker
# - npm install --global check-pages-cli fkill-cli http-server mkcert pa11y-ci
# - choco install googlechrome --yes
# - choco install gtools --yes --force
# - refreshenv
# - pathed /APPEND %PYTHON% /USER
# - pathed /APPEND %PYTHON%\Scripts /USER
# - refreshenv
# - reg import appveyor/EnableUnicodeUTF8Worldwide.reg
# - shutdown /r /t 0

# before_build:
# - echo %NODE_TLS_REJECT_UNAUTHORIZED%
# - echo %PATH%
# - refreshenv
# - echo %PATH%

build_script:
- where gnuplot
- gnuplot --version
- where python
- python --version
- where pip
- pip --version
- where linkchecker
- linkchecker --version
