init:
- set PATH=%GOPATH%\bin;c:\go\bin;%PATH%

environment:
  GOPATH: c:\gopath

build_script:

- mkdir c:\gopath\src\github.com\asciinema
- cd c:\gopath\src\github.com\asciinema
- git clone https://github.com/mattn/asciinema
- cd asciinema
- git checkout windows
- go get -d
- go build