platform: x64

image: Visual Studio 2022

clone_depth: 1

install:
- choco install nodejs fd -y
- npm install --global @coffeelint/cli

build_script:
- where coffeelint
- "fd -0 -e coffee | xargs -0 coffeelint"
