init:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - set PYTHONIOENCODING=utf-8

environment:

  matrix:

    - PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: "3.6.4"
      PYTHON_ARCH: "64"
      nodejs_version: "Current"

install:
  - ps: Install-Product node $env:nodejs_version

platform: x64

build_script:

  - node --version