platform: x64

image: Visual Studio 2022

clone_depth: 1

cache:
- C:\ProgramData\chocolatey\bin
- C:\ProgramData\chocolatey\lib
- "%USERPROFILE%\\AppData\\Roaming\\npm\\node_modules"
# - "%APPVEYOR_BUILD_FOLDER%/node_modules"

environment:
  nodejs_version: "21"

install:
- reg import appveyor/EnableUnicodeUTF8Worldwide.reg
- shutdown /r /t 0
# - ps: Restart-Computer
# - timeout 10
- reg import appveyor/EnableChcp65001.reg
- choco install html-tidy --version=5.6.0 --allow-downgrade --ignore-dependencies
- npm install --global htmlhint

before_build:
- chcp
- node --version
- tidy --version
- htmlhint --version

build_script:
- htmlhint KiraValidHTML.html
- htmlhint КираВалидныйHTML.html
- tidy --quiet yes KiraValidHTML.html
- tidy --quiet yes КираВалидныйHTML.html
