init:
- SET PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
- SET PYTHONIOENCODING=utf-8

environment:
  matrix:
  - PYTHON: C:\Python36-x64
    PYTHON_VERSION: 3.6.4
    PYTHON_ARCH: 64

platform: x64

install:
- pip install bashate

build_script:
- where bashate
- bashate -i E002,E003,E006,E010,E011 shellcheck.sh