environment:

  matrix:

    - PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: "3.6.4"
      PYTHON_ARCH: "64"

platform: x64

init:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - chcp 65001
  - set PYTHONIOENCODING=utf-8

install:
  - pip install pipenv
  - pipenv install --dev

build_script:

  - pipenv --version
  - pelican --version