platform: x64

image: Visual Studio 2022

clone_depth: 1

cache:
# - C:\ProgramData\chocolatey\bin
# - C:\ProgramData\chocolatey\lib
- "%USERPROFILE%\\AppData\\Roaming\\npm\\node_modules"
# - "%APPVEYOR_BUILD_FOLDER%/node_modules"

environment:
  nodejs_version: "21"

install:
- reg import KiraUnicodeCmd.reg
# - shutdown /r
- ps: Restart-Computer
# - choco install html-tidy --version=5.6.0 --allow-downgrade --ignore-dependencies
- npm install --global htmlhint

before_build:
- node --version
- htmlhint --version
- chcp

build_script:
- htmlhint KiraValidHTML.html
- htmlhint КираВалидныйHTML.html
