environment:
  PYTHON: C:\Python310-x64

platform: x64

clone_depth: 1

image: Visual Studio 2019

init:
- SETX PIPENV_IGNORE_VIRTUALENVS 1
- SETX PIPENV_VENV_IN_PROJECT 1
# [NOTE] Needs AppVeyor console set, see:
# https://stackoverflow.com/a/48093971/5951529
- SETX PYTHONIOENCODING utf-8

install:
- "%APPVEYOR_BUILD_FOLDER%/appveyor-pathed.bat"
- refreshenv
- "%APPVEYOR_BUILD_FOLDER%/appveyor-install.bat"
- refreshenv

build_script:
- pipenv run pelican --version