environment:
  PYTHON: C:\Python39-x64

platform: x64

image: Visual Studio 2022

init:
- SETX PIPENV_IGNORE_VIRTUALENVS 1
- SETX PIPENV_VENV_IN_PROJECT 1
# [NOTE] Needs AppVeyor console set, see:
# https://stackoverflow.com/a/48093971/5951529
- SETX PYTHONIOENCODING utf-8

install:
- "%PYTHON%\\python -m pip install --upgrade pip & %PYTHON%\\python -m pip install pipenv & pipenv install --dev & pipenv run peru sync"

build_script:
- pipenv run pelican --version