platform: x64

image: Visual Studio 2013

clone_depth: 1

cache:
- C:\ProgramData\chocolatey\bin
- C:\ProgramData\chocolatey\lib
- "%USERPROFILE%\\AppData\\Roaming\\npm\\node_modules"
- "%APPVEYOR_BUILD_FOLDER%/node_modules"

environment:
  nodejs_version: "21"

before_build:
- where node
- where npm

install:
- ps: Install-Product node $env:nodejs_version
- npm install --global @coffeelint/cli
- npm install --save-dev @coffeelint/cli

build_script:
- <KiraList.txt xargs --replace=KiraFilename coffeelint KiraFilename
- <KiraList.txt xargs --replace=KiraFilename npx coffeelint KiraFilename
