platform: x64

image: Visual Studio 2022

install:
- choco install nodejs -y
- npm install -g postcss-cli doiuse editorconfig-checker

build_script:
- more KiraExampleCSS.css
- postcss KiraExample.css -u doiuse -o KiraPostCSS.css
- more KiraPostCSS.css
- editorconfig-checker
