clone_depth: 1

platform: x64

environment:
  PYTHON: "C:\\Python37-x64"
  PYTHON_VERSION: 3.7
  PYTHON_ARCH: 64
  PYTHON_SCRIPTS: "C:\\Python37-x64\\Scripts"

install:
# As in Ruby example:
# https://www.appveyor.com/docs/lang/ruby/#installation
- set PATH=C:\Python37-x64\Scripts;%PATH%
# [INFO] python-appveyor-demo:
# https://github.com/ogrisel/python-appveyor-demo/blob/master/appveyor.yml
- "SET PATH=C:\\Python37-x64\\%PYTHON%\\Scripts;%PATH%"
- refreshenv
- "%PYTHON%\\python -m pip install --upgrade pip"
- "%PYTHON_SCRIPTS%\\pip install erichek"

build_script:
- "%PYTHON_SCRIPTS%\\pip --version"
- "%PYTHON%\\python --version"
- erichek --help
