clone_depth: 1

platform: x64

init:
- SET "PATH=%PATH%;%PYTHON%;%PYTHON%\\Scripts"
- SET PATH=%PATH:C:\Python27;=%
- SET PATH=%PATH:C:\Python27\Scripts;=%
- refreshenv

configuration:
- Debug
- Release

environment:
  PYTHON: C:\Python37-x64
  PYTHON_VERSION: 3.7
  PYTHON_ARCH: 64
  PIP: "C:\\Python37-x64\\Scripts\\pip"
  KIRA_VARIABLE: Queen

build_script:
- echo %KIRA_VARIABLE%
- echo %PATH%
- echo %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%
- python --version

for:
-
  matrix:
    only:
    - configuration: Release
  environment:
    KIRA_VARIABLE: Goddess