configuration:
- Debug
- Release

for:
  matrix:
  	GRUNT_BUILD_SCRIPT: Debug Goddess
  	only:
  	  - configuration: Release
  	    GRUNT_BUILD_SCRIPT: Release Goddess

platform: x64

build_script:
- echo %GRUNT_BUILD_SCRIPT%