platform: x64

image: Visual Studio 2022

clone_depth: 1

install:
- choco install nodejs -y
- npm install -g postcss-cli doiuse editorconfig-checker

build_script:
- postcss KiraExampleCSS.css -u doiuse -o KiraPostCSS.css

test_script:
- more KiraExampleCSS.css
- more KiraPostCSS.css
- editorconfig-checker
