configuration:
- Debug
- Release

environment:
  GRUNT_BUILD_SCRIPT: DebugSasha Goddess

for:
-
  matrix:
    only:
    - configuration: Release
      GRUNT_BUILD_SCRIPT: ReleaseKira Goddess

platform: x64

build_script:
- echo %GRUNT_BUILD_SCRIPT%