build_script:
- npm --version

# cache:
# - "%LOCALAPPDATA%\\npm-cache"
# - "%LOCALAPPDATA%\\pip\\cache"
# - "%LOCALAPPDATA%\\pipenv\\pipenv\\cache"

clone_depth: 1

deploy:
  provider: Script

deploy_script: echo "Kira Goddess!"

environment:
  APPVEYOR_SAVE_CACHE_ON_ERROR: true

image: Visual Studio 2022

install:
- node --version

platform: x64
