clone_depth: 1

configuration:
- Debug
- Release

environment:
  GRUNT_BUILD_SCRIPT: DebugSasha Goddess

build_script:
- echo %GRUNT_BUILD_SCRIPT%

for:
-
  configuration: Release
  environment:
    GRUNT_BUILD_SCRIPT: ReleaseKira Goddess
