platform: x64

image: Visual Studio 2022

clone_depth: 1

environment:
  APPVEYOR_SAVE_CACHE_ON_ERROR: true
  # nodejs_version: "21"
  PYTHON: C:\Python312-x64
  PATH: "%PYTHON%;%PYTHON%\\Scripts;$(PATH)"


cache:
# - C:\ProgramData\chocolatey\bin
# - C:\ProgramData\chocolatey\lib
# - "%USERPROFILE%\\AppData\\Roaming\\npm"
# - "%APPVEYOR_BUILD_FOLDER%\\node_modules"
- "%PYTHON%\\Lib\\site-packages"
- "%PYTHON%\\Scripts"
# - "%APPVEYOR_BUILD_FOLDER%\\.venv\\Lib\\site-packages"
# - "%APPVEYOR_BUILD_FOLDER%\\.venv\\Scripts"

# init:
# - SETX NODE_TLS_REJECT_UNAUTHORIZED 0
# - SETX /m PATH "%PATH%;%PYTHON%\Scripts"

install:
# - npm install --global check-pages-cli fkill-cli http-server mkcert pa11y-ci
- "%PYTHON%\\python -m pip install linkchecker"
# - choco install googlechrome --yes
# - choco install gtools --yes --force
# - refreshenv
# - pathed /APPEND %PYTHON% /USER
# - pathed /APPEND %PYTHON%\Scripts /USER
# - refreshenv

before_build:
- echo %PATH%

build_script:
- python --version
- where linkchecker
- linkchecker --version
