clone_depth: 1

init:
- SETX PATH "%PATH%;%USERPROFILE%\.dotnet\tools"
- refreshenv

configuration:
- Debug
- Release

environment:
  GRUNT_BUILD: Kira
  APPVEYOR_API_KEY:
    secure: +tAYCLWvKpNefBmIFHBZzSdFnN8mu71hBU1MqYbrjlY=

install:
- dotnet tool install -g localappveyor --version 0.5.0-alpha.10

build_script:
- echo %GRUNT_BUILD%
- echo %PATH%

test_script:
- cd "%USERPROFILE%\.dotnet\tools" && dir
- cd %APPVEYOR_BUILD_FOLDER%
- echo %PATH%
- LocalAppVeyor lint --token %APPVEYOR_API_KEY%

for:
-
  matrix:
    only:
    - configuration: Release
  environment:
    GRUNT_BUILD: Goddess