platform: x64

image: Visual Studio 2022

environment:
  PYTHON: C:\Python310-x64

init:
- SETX PIPENV_IGNORE_VIRTUALENVS 1
- SETX PIPENV_VENV_IN_PROJECT 1
- SETX PIPENV_SKIP_LOCK 1
- SETX PYTHONIOENCODING utf-8
- "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

install:
- "%PYTHON%\\python -m pip install pipenv"
- pipenv install --dev --verbose

build_script:
- pipenv --version
