clone_depth: 1

init:
- SETX PIPENV_IGNORE_VIRTUALENVS 1
- SETX PIPENV_VENV_IN_PROJECT 1
- SETX PATH "PATH=C:\Ruby25-x64\bin;%PATH%"
- SETX PATH "PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%"
- SETX PYTHONIOENCODING utf-8
- SETX DOTNET_CLI_TELEMETRY_OPTOUT 1

build_script:
- echo "Kira Goddess!"
