clone_depth: 1

# environment:
#   APPVEYOR_SAVE_CACHE_ON_ERROR: true

image: Visual Studio 2022

platform: x64

# cache:
# - "%LOCALAPPDATA%\\npm-cache"
# - "%LOCALAPPDATA%\\pip\\cache"
# - "%LOCALAPPDATA%\\pipenv\\pipenv\\cache"

install:
- choco install --yes fd git shellcheck

before_build:
- fd --version
- shellcheck --version
- where sh
- sh --version
- where echo
- echo --version
- where git
- git --version

build_script:
- fd --extension sh | xargs --replace=% echo "echo %; shellcheck %" | sh
