clone_depth: 1

init:
- SETX PATH "%PATH%;%USERPROFILE%\.dotnet\tools"

environment:
  APPVEYOR_API_KEY:
    secure: +tAYCLWvKpNefBmIFHBZzSdFnN8mu71hBU1MqYbrjlY=

install:
- dotnet tool install -g localappveyor --version 0.5.0-alpha.10

build_script:
- echo %PATH%
- cd "%USERPROFILE%\.dotnet\tools" && tree /f

test_script:
- LocalAppVeyor lint --token %APPVEYOR_API_KEY%
