clone_depth: 1

init:
- SETX PATH "%PATH%;%USERPROFILE%\.dotnet\tools"
- refreshenv

configuration:
- Debug
- Release

environment:
  # Variables:
  # https://help.appveyor.com/discussions/problems/4629-how-to-use-appveyor-environment-variable
  # https://help.appveyor.com/discussions/questions/15163-multiuple-build-matrix-dimensions-from-environment-variables
  PYTHON: C:\Python37-x64
  PYTHON_VERSION: 3.7
  PYTHON_ARCH: 64
  GRUNT_BUILD: Kira
  APPVEYOR_API_KEY:
    secure: +tAYCLWvKpNefBmIFHBZzSdFnN8mu71hBU1MqYbrjlY=

install:
- dotnet tool install -g localappveyor --version 0.5.0-alpha.10

build_script:
- echo %GRUNT_BUILD%

test_script:
- cd "%USERPROFILE%\.dotnet\tools" && dir /s /b /a
- cd %APPVEYOR_BUILD_FOLDER%
- echo %PATH%
- LocalAppVeyor lint --token %APPVEYOR_API_KEY%

for:
-
  matrix:
    only:
    - configuration: Release
  environment:
    GRUNT_BUILD: Goddess