clone_depth: 1

platform: x64

environment:
  PYTHON: C:\Python37-x64
  RUBY: C:\Ruby26-x64\bin

install:
- choco install gtools -y
- refreshenv

build_script:
- where pathed
- pathed /APPEND %PYTHON%
- pathed /APPEND %RUBY%
- echo %PATH%