##########
# pylint #
##########
# [OVERVIEW] Pylint — Python static code analyser:
# https://pylint.pycqa.org/en/latest/index.html
#
# [RULES]
# https://pylint.pycqa.org/en/latest/user_guide/checkers/features.html
# https://pylint.pycqa.org/en/latest/user_guide/messages/messages_overview.html
#
# [CONFIGURATION]
# https://github.com/PyCQA/pylint/blob/master/pylintrc
# https://pylint.pycqa.org/en/latest/user_guide/configuration/all-options.html
# https://www.getcodeflow.com/pylint-configuration.html
#
# [OPTIONS] CLI options:
# https://megalinter.io/latest/descriptors/python_pylint/#help-content
# https://pylint.pycqa.org/en/latest/user_guide/usage/run.html#command-line-options
#
# [FAQ]
# https://pylint.pycqa.org/en/latest/faq.html
#
# [API] API for using Pylint, symilar and pyreverse in another Python programs:
# https://pylint.pycqa.org/en/latest/development_guide/api/index.html
# https://pylint.pycqa.org/en/latest/development_guide/api/pylint.html
#
# [PLUGINS] Built-in optional plugins/extensions:
# https://pylint.pycqa.org/en/latest/user_guide/checkers/extensions.html
#
#
# [FIXME][TRY] Additional Python linters and formatters:
# https://pylint.pycqa.org/en/latest/index.html#advised-linters-alongside-pylint
#
# [INFO] To set correct “pylintrc.toml” file, run “pylint --generate-toml-config”
# and look at the correct Pylint section names in the TOML file:
# https://pylint.pycqa.org/en/latest/user_guide/configuration/index.html


[tool.pylint.main]

# [INFO] Ignoring specific directories in Pylint:
# https://stackoverflow.com/a/8427174/5951529
#
# [INFO] I ignore all third-party, not my own code
#
#
# [LEARN][TOML] Long lines in TOML:
# https://github.com/toml-lang/toml/issues/163#issuecomment-656007706
ignore = ".venv, node_modules, pelican-plugins"

# [INFO] Run Pylint recursively — “pylint --recursive=y .”:
# https://stackoverflow.com/a/73227403/5951529
# https://pylint.pycqa.org/en/latest/user_guide/configuration/all-options.html#recursive
recursive = true


[tool.pylint.format]

# [INFO] Default value is 100. I use 120 for any file format:
# https://pylint.pycqa.org/en/latest/user_guide/configuration/all-options.html#max-line-length
max-line-length = 120


[tool.pylint."messages control"]

# [INFO] Disable rules or extensions in Pylint:
# https://bobbyhadz.com/blog/disable-pylint-warning
#
# [INFO] In Pylint it is possible to disable both by rule name and error code:
# “disable = "empty-comment"” and “disable = "R2044"” both valid.
#
# [INFO] I don’t use the extension “pylint.extensions.empty_comment”,
# because I use empty comments for readability:
# https://pylint.pycqa.org/en/latest/user_guide/checkers/extensions.html#empty-comment-checker
disable = "empty-comment"


[tool.pylint.reports]

# [INFO] Add colors to output:
# https://pylint.pycqa.org/en/latest/user_guide/configuration/all-options.html#output-format
output-format = "colorized"
